### ISSUE TITLE
clearing AnySelectionTable does not clear sub-selectionmodels

### ISSUE THREAD

**Issue by psymagic** [wandora-team/wandora#10]
Just a minor issue:

As anyselectiontable is build in a downward compatible way with a standard table, I have been using getSelectedRow+ getSelectedRows and respectively Columns for the boundaries in conjunction with isSelected for the individual cells.

Thus, I discovered that AnySlectionTable.java overrides clearSelection in a way that does only clear its onw introduced Table Model but not the underlying built-in ones.

For full backwards compatibility that method must be changed as follows:

`    @Override`
`    public void clearSelection() {`
`        if (tableSelectionModel != null) {`
`            tableSelectionModel.clearSelection();`
`        }`
**`        super.getSelectionModel().clearSelection();`
`        super.getColumnModel().getSelectionModel().clearSelection();`**
`        this.repaint();`
`    } `

**Comment by akivela** [comment]
Thank you for the issue. I have fixed AnySelectionTable's clearSelection method as you suggested.
