### ISSUE TITLE
"generate" counterintuitive

### ISSUE THREAD

**Issue by danmbox** [wandora-team/wandora#3]
The effect of the various generators (I've tried Random and Fully connected) from "Generate to layer" is at least counterintuitive (if they actually do something). There are no apparent changes, and the generated graph doesn't appear in the default tree panel, or in any of the panels I've tried (View / New Panel).

**Comment by akivela** [comment]
Hi Dan. You can easily find created topics by searching "Topic" with Finder. Topics created by the Random generator are named as "Topic n" where n is an integer number starting from 0. Also, if you look carefully numbers in parenthesis at the lower right corner of Wandora application window, just beside the layer name, you may notice the numbers change during a generator action. First number indicates the number of topics in current layer and the second number of associations in the layer. When you start Wandora, the Base layer has 29 topics and 19 associations (at this time). There is also other ways of detecting changes in the topic map. Layer info panel (View > New panel > Layer info) is one of such.

But thinking of the original issue of not seeing generated topics and associations in the Topics tab. The Topics tab is just one view to the topic map and relies on associations between topics. Attaching generated topics to the Topics tab or any other topic tree requires some additional/supporting topics and associations which add noise to the output of generator. Till now the principle has been to keep such additional/supporting topics and associations minimal and rely the user can find and connect generated topics to the Topics tab (or any topic tree).

**Comment by danmbox** [comment]
Thanks. A couple of points (some probably easier to take into account than others):

1. http://wandora.org/wiki/Random_graph_generator makes it seem as though you can easily go from generating a random graph to a cool visualization, when, in fact there are a few non-obvious steps that are not clear to me.

2. What "additional/supporting topics and associations" do I need to add to make the generated graph visible in any of the common tabs / panels? How come the Topics tab doesn't "see" the new associations? Perhaps the missing stuff could be *optionally* auto-generated?

3. Allowing the user to change the default "Topic" prefix might be nice - - e.g. what if we "Generate" twice?

4. Either a warning dialog, and/or directly bringing up the appropriately pre-filled Search panel might help with usability.

**Comment by akivela** [comment]
Good points, Dan.

1. The generator could indeed ask whether the user wants to view generated graph. Now the user must open any of the generated topics, Topic 0, for example, into the Graph panel (View > Add panel > Graph, see http://wandora.org/wiki/Graph_topic_panel) and expand the graph to view all connected nodes. Oh, there is one point that may cause problems. If the generated graph is large (>1000 topics), it is very likely that the current implementation of graph visualization chokes and freezes the application.

2. Good idea: Optionally add supporting topics and associations to the graph. I'll put this into my work list. Why the Topics tab doesn't see new associations? This relates to the behavior of topic tree. The tree doesn't view all topics the user has, but only specific descendents of a specific root topic. By default the root topic is "Wandora class" but the user can change it. Specific descendents are topics that are connected to the root and it's descendents with a set of given associations. These given associations are by default class-instance-relation and subclass-superclass-relation. The user can change the set of associations that specify tree branches. As topic maps can have associations of any type, the tree doesn't see everything. See also Wandora documentation at http://wandora.org/wiki/Working_with_topic_trees and http://wandora.org/wiki/Creating_custom_topic_trees .

3. Good idea: Change the default prefix "Topic". Addition to the basename prefix, I think changing the subject identifier prefix could be a good idea, as well, as changing the association type and roles. If the user generates twice with same settings, topics created during the first round merge with topics generated during first round. Wandora merges topics if they share same basename or subject locator or subject identifier. Identical associations merge too. Thinking of a Random graph generator, running it twice to generate 100 topics and 500 association would end up with a topic map with 100 (+association type and role topics) and 500-1000 associations. Association number varies as some associations of second round merge with the associations generated during the first round.

4. Good idea.

Obviously these ideas cover a broader set of generators than just Random graph and Fully connected graph generator. Same issue of spotting generated topics is relevant for other generators too.

**Comment by akivela** [comment]
Wandora release 2015-04-20 adds most generators options to change created topics and associations, and to connect generated topics with Wandora's base ontology.
