### ISSUE TITLE
add DB transactions around generators, extractors (performance)?

### ISSUE THREAD

**Issue by danmbox** [wandora-team/wandora#5]
I'm seeing poor performance with a database layer (sqlite in my case) for generators and extractors. I _think_ (after `strace`-ing) that it's due to the way Wandora issues single SQL statements to the database underlying the layer abstraction, thus effectively forcing a commit for every single operation. Would it be possible to wrap multi-step sequences (like the stuff in `FullyConnectedGraphGenerator.java`) in `BEGIN`...`COMMIT` transactions? I'm guessing the layer interface would need an extra method or two.

This would also avoid partially-completed extractions / generations.

**Comment by akivela** [comment]
All suggestions to speed up the database implementation of a topic map are welcome. All topic map features in Wandora, FullyConnectedGraphGenerator.java among others, use api that is independent of the actual storage implementation. Thus, one can't add optimization into the tool (WandoraTool.java) level but on the topic map level. In this case, the optimization would go to the database implementation of topic map i.e. classes in package org.wandora.topicmap.database. Specific classes are DatabaseTopicMap.java, DatabaseTopic.java and DatabaseAssociation.java. I would be very happy if you can suggest improvements for the current implementation. However, remember, Wandora's topic map model is auto-merging. Adding topics and associations may trigger rather complex side-effects.

**Comment by danmbox** [comment]
I see, this is not easy... Once you go below the semantic level (i.e. at the topic map level or database level) it's impossible to know which actions are related (and should be part of a database transaction) and which are not related, right?

By the way, since transactions aren't used, how do you ensure atomicity in case of crashes? E.g. what happens if the computer (or wandora) crashes in the middle of an extraction operation? Do you have other journalling mechanisms at the application level?

**Comment by akivela** [comment]
You got it right. It isn't straightforward to implement transactions to current database topic map implementation.

At the moment the database topic map implementation doesn't ensure atomicity. This means the database may end up inconsistent if the application crashes. Even less radical exceptions are difficult: Two or more users editing same database may cause inconsistent database too. It just requires the SQL statements interleave appropriately. At the moment there is no journalling nor any other mechanisms to prevent this happening.

Want to try to improve the current status?

**Comment by danmbox** [comment]
Of course (I don't know the architecture though, obviously). Let's see: from within generators / extractors, do we have access to something like a global application singleton? I'm envisioning something like:

theApp.startTransaction()
// extract
theApp.endTransaction()

where startTransaction (in the global Application object) is

for (l : layers) l.startTransaction()

(and memory layers would ignore transactions).

**Comment by akivela** [comment]
Sounds promising. I discussed the issue with Olli (olligrip) yesterday and he suggested similar approach. I have now added git's master branch initial preparations for the transactional topic maps (https://github.com/wandora-team/wandora/commit/83825b420a65def85162a1836c12bcec9397fbe3). At the tool class level you can call methods:

    wandora.startTransaction();
    wandora.endTransaction();

Here 'wandora' is an instance of Wandora. It comes as an argument to the execute method of the tool. If you want to use the methods in static context, use:

    Wandora.getWandora().startTransaction();
    Wandora.getWandora().endTransaction();

Wandora class propagates the call to the current topic map:

    public void startTransaction() {
        if(topicMap != null) {
            topicMap.startTransaction();
        }
    }
    
    public void endTransaction() {
        if(topicMap != null) {
            topicMap.endTransaction();
        }
    }

Currently Wandora uses LayerStack as the default topic map. It propagates the method call to all enclosed topic maps:

    public void startTransaction() {
        for(Layer l : visibleLayers){
            l.getTopicMap().startTransaction();
        }
    }
    
    public void endTransaction() {
        for(Layer l : visibleLayers){
            l.getTopicMap().endTransaction();
        }
    }

All topic map implementation inherit these startTransaction and endTransaction methods from abstract org.wandora.topicmap.TopicMap. Inherited methods are empty, by default a topic maps doesn't support transactions. Any topic map implementation supporting transactions should override these methods.

If you want to continue, make a copy of Wandora's database topic map implementation in package org.wandora.topicmap.database, rename it and start experimenting. First you should implement the actual startTransaction and endTransaction methods in the topic map. The RandomGraphGenerator and other generators may work as a good test source.

**Comment by danmbox** [comment]
Well, so long as we're implementing transactions, why not give the full BEGIN / COMMIT / ROLLBACK interface? Thus cancelling a long extraction / generation would lead to a ROLLBACK. The only problem is that the in-memory implementation would become "officially buggy" (since you're not tracking, you can't easily roll back).

Also, the potential for bugs exists in tools (generators, extractors etc), not in the topic map implementation. The risk is that some tool calls startTransaction(), but forgets to commit or rollback (perhaps via an unhandled exception). I'm not sure if "forking" DatabaseTopicMap.java will help much. Some day, someone will forget to close the transaction...

**Comment by akivela** [comment]
Dan, you have valid points there. I prefer not to solve the whole transactions/rollback issue at once but let you start experimenting and getting to know the Wandora in the first place. Once we see the transactions significantly speed up the random graph generator over the transactional database topic map, we'll look at the transactions/rollback issue much more seriously. Till now, improving the database topic map has not been on our focus. See the current transaction interface (with startTransaction and endTransaction methods) just a first step that will be changed/improved once we have more clear vision of requirements/possibilities of the transactional topic maps.

You may have noticed that Wandora supports undo/redo feature for all topic map editions. This is implemented with a wrapper topic map implementation in UndoTopicMap. Thus, we already have a kind of rollback for memory topic map (as well as database topic maps). It just doesn't work at the database level but application level.
