### ISSUE TITLE
So interesting application and so unknown.

### ISSUE THREAD

**Issue by Losiara** [wandora-team/wandora#6]
I am looking for similar app for several years. Tried much mindmaps, conceptmap etc etc huge amounts. All didn't like. But very randomly found wandora and it covered all my needs? Why it is so little presented in the Internet in spite of the fact that it is rather old?

**Comment by akivela** [comment]
Hi Losiara

Thanks for your message. I am very pleased you found Wandora. Why is Wandora so little presented? It is hard to say but my guess is that

- Wandora Team has only few people and we don't make this for living -- no money involved. Thus, we don't have resources to make much noise about the application. Neither is there any background or supporting organizations that would really push Wandora forward.
- Wandora is based on Topic Maps technology. Topic Maps are not a main stream technology. In fact, Topic Maps are underestimated and dismissed by most of the players in the Semantic Web and Linked Data field.
- Wandora is rather complicated software. It requires some time to understand the basic features and possibilities of the application. Wandora has it's own flavor/paradigm of doing things and requires some adaptation from the user's point of view.
- Wandora is an ongoing project and the application contains bugs and unfinished features, I have to admit. This may drive away some potential users seeking more stable systems.

In any case, as I wrote above, I feel very pleased you found Wandora. I wish you have the time and patience to experiment with the application, and perhaps even contribute something to the project. Please don't hesitate to ask if you have anything in your mind about the Wandora.

**Comment by Losiara** [comment]
Thank you for app. I am more in cpp/python than java. But may be will help smt if go on with this app.
