### ISSUE TITLE
Clarify development status of Facebook Graph extractor

### ISSUE THREAD

**Issue by jcahill** [wandora-team/wandora#8]
#### Outdated docs

The [wandora wiki page][1], last updated in 2010, is for an [app][2] no longer used by the Wandora tool.

```json
{
   "category": "Utilities",
   "link": "http://www.wandora.org/fb/",
   "name": "Wandora",
   "id": "45942818365"
}
```

#### Old Facebook App Still Live

The old facebook app is still live, despite being nonfunctional. This seems like an oversight, since it can still be added by users, e.g. those arriving via the wiki, and will collect their public profile information. Users receiving a 500 error after redirect to wandora.org may not realize that they've succeeded in adding the app.

#### Current Facebook App *Not* Live

The current version of Wandora launches http://wandora.org/fbv2/. This app's status is set to In Development, so it cannot be used.

#### App Uses Unavailable API Version

The v2 app's oauth dialog link specifies graph API v2.3, which has been [unavailable][3] since 2017-07-08.

Many projects have been abandoned since v2.3, so it would be helpful to know whether a Wandora update is planned.

---

[1]: http://wandora.org/wiki/Facebook_Graph_extractor
[2]: https://www.facebook.com/dialog/oauth?client_id=45942818365&redirect_uri=http%3A%2F%2Fwww.wandora.org%2Ffb%2F
[3]: https://developers.facebook.com/docs/graph-api/changelog/archive

**Comment by akivela** [comment]
Hello @jcahill 

Thank you for trying Wandora and Wandora's Facebook extractor, and thank you for the question.

I'll check if it is possible to update Wandora's Facebook V2 extractor for the current Facebook API version. If the required work is small enough, I'll do it. I'll post another comment once I know more.

**Comment by akivela** [comment]
Hello @jcahill 

As you may have seen, Facebook is planning radical changes to the graph API after The Guardian revealed Cambridge Analytica had used millions of Facebook users' data illegally. We have decided to wait until it is clear how the planned changes affect graph API usage, before fixing Wandora's Facebook extractor. It is also possible that we'll *not* fix nor update the extractor if the terms become too restrictive or difficult.

**Comment by jcahill** [comment]
@akivela Yes, unfortunately. I've been tracking the story for years now, and I'm sure many others with noncommercial research interest in this type of network modeling have as well. Makes it all the more frustrating to see these events go nuclear now. I inquired because of how apparent the extent of die-off for facebook-facing tooling has already been prior to the current meltdown.

netvizz and fbarc are the only tools I'm aware of that continue to do anything substantive enough to be useful in this domain. netvizz was already slated to lose its ability to generate graphical information with Facebook's GDPR API update this month, however. The current PR crisis might do in what little flexibility remains.

Thanks for the followup.
