### ISSUE TITLE
AnySelectionTable does not disable properly

### ISSUE THREAD

**Issue by psymagic** [wandora-team/wandora#9]
Thanks for the Table, has been really helpful to work around swings inherent limitations.

Now to the problem:
When the table is disabled, selection is still possible.

Possible solution:
add this to `mouseDragged `and `mousePressed `in **AnySelectionTableUI**
```
            JTable t = getTable();
            if(!t.isEnabled()) {
                return;
            }
```

**Comment by akivela** [comment]
Psymagic, thank you for your report related to the AnySelectionTable.
